"""Pydantic response/request models for the JSON REST API.

All models are re-exported here for backward compatibility.
Import from ``src.web.schemas`` or individual sub-modules.
"""

from src.web.schemas.advisor import (
    HolidayImpactFactor,
    HolidayImpactResult,
    PortfolioAdviceRequest,
    PortfolioAdviceResult,
    PositionAdvice,
    PositionImpact,
    QuantSignals,
    ReopenBriefingResult,
    StockAdviceResult,
    TargetPrice,
    WatchlistStrategyItem,
    WatchlistStrategyResult,
)
from src.web.schemas.sentiment import (
    CrossMarketGroup,
    CrossMarketPeer,
    CrossMarketResult,
    ResonanceEventItem,
    ResonanceResult,
    ResonanceTimelineEntry,
    SentimentCoreTrend,
    SentimentGlobalLinkage,
    SentimentPolicySignal,
    SentimentReportResult,
    SentimentRiskAlert,
    SentimentSectorOutlook,
)
from src.web.schemas.scheduler import (
    CalendarDay,
    CalendarResult,
    NotificationChannelConfig,
    SchedulePlan,
    SchedulePlansResult,
    SchedulerStatus,
    SentinelConfig,
    TaskConfig,
    UpdatePlanRequest,
)
from src.web.schemas.holiday_research import (
    AddEvidenceRequest,
    AddNoteRequest,
    AssociationProfileResponse,
    BusinessFactor,
    ComprehensiveAnalysisResult,
    ConceptLinkResponse,
    ConversationMessage,
    EvidenceItem,
    FollowupRequest,
    FollowupResponse,
    HolidayResearchContext,
    IndustryProfileResponse,
    PeerComparison,
    PeerLinkResponse,
    ProfileOverrideConceptItem,
    ProfileOverridePeerItem,
    ProfileOverrideRequest,
    ProfileOverrideResponse,
    ReopeningStrategy,
    ResearchChecklist,
    ResearchQuestion,
    RiskItem,
    Scenario,
    ScenarioAnalysisRequest,
    ScenarioAnalysisResult,
    ScenarioPriceImpact,
    ScenarioResult,
    SectorAnalysis,
    UserNote,
)
from src.web.schemas.concept import (
    ConceptConstituentItem,
    ConceptHeatListResponse,
    ConceptHeatResponse,
    ConceptHistoryRecord,
    ConceptLeader,
    ResonanceResponse,
    StockConceptItemResponse,
    StockConceptsResponse,
)
from src.web.schemas.admin import (
    AddKeyRequest,
    ApiKeyInfo,
    RoutingConfig,
    UpdateRoutingRequest,
    UsageDashboard,
)
from src.web.schemas.analysis import (
    AIAnalysisResult,
    Alert,
    BayesianAnalysisResult,
    BayesianComposite,
    BayesianIndicatorItem,
    ChartEvent,
    ChartEventsResult,
    IndicatorExplanation,
    IndicatorProbabilities,
    MoveAnalysisFactor,
    MoveAnalysisPositionContext,
    MoveAnalysisRequest,
    MoveAnalysisResult,
)
from src.web.schemas.backtest import (
    AttributionData,
    BacktestInterpretRequest,
    BacktestInterpretResult,
    BacktestMetrics,
    BacktestRequest,
    BacktestRequestV2,
    BacktestResponse,
    BacktestResponseV2,
    RoundTripItem,
    StrategyFlowEdge,
    StrategyFlowStep,
    StrategyInfo,
    StrategyMetadataResponse,
    StrategyParam,
    TradeSignalItem,
)
from src.web.schemas.common import ApiResponse, MarketAIOverview
from src.web.schemas.fund_flow import (
    FundFlowDetail,
    FundFlowItem,
    SRAnalysisResult,
    SRKeyLevel,
)
from src.web.schemas.market import (
    DragonTigerAIResult,
    DragonTigerItem,
    DragonTigerSeatItem,
    DragonTigerStockStats,
    GlobalCommodityItem,
    GlobalCurrencyItem,
    GlobalIndexItem,
    GlobalMarketSnapshot,
    HotRankItem,
    LimitUpItem,
    MarketIndex,
    TradingCalendarInfo,
)
from src.web.schemas.news import (
    AnomalyItem,
    ResearchResult,
    SentimentSummary,
    StockNewsItem,
)
from src.web.schemas.notification import NotificationItem, UnreadCountResponse
from src.web.schemas.portfolio import (
    ConcentrationRisk,
    PortfolioData,
    PortfolioDiagnosisRequest,
    PortfolioDiagnosisResult,
    PortfolioPosition,
    PortfolioPositionInput,
    PositionAdviceItem,
)
from src.web.schemas.prediction import (
    ComparisonPredictionRequest,
    ComparisonPredictionResult,
    EnhancedPredictionRequest,
    EnhancedPredictionResult,
    PredictionRequest,
    PredictionResult,
    QuickInsight,
)
from src.web.schemas.settings import (
    UpdateConfigRequest,
    WatchlistAddRequest,
    WatchlistRemoveRequest,
    WatchlistUpdateRequest,
)
from src.web.schemas.stock import (
    FundFlowDetailSnapshot,
    FundFlowSnapshot,
    IndicatorsFullRecord,
    IndicatorsSummary,
    IntradayTradesSnapshot,
    IntradayTradesStats,
    OHLCVRecord,
    PatternDetection,
    QuoteSnapshot,
    RealtimeQuote,
    RealtimeSnapshot,
    StockDetail,
    StockSearchItem,
    SupportResistanceLevel,
    TickRecord,
    WatchlistItem,
)
from src.web.schemas.conversation import (
    ConversationMessageItem,
    ConversationRequest,
    ConversationResponse,
    PositionContext,
)
from src.web.schemas.chat import (
    ChatMessage,
    ChatThread,
    CreateThreadRequest,
    CreateThreadResponse,
    RichCard,
    SendMessageRequest,
    ThreadContext,
    ThreadListItem,
    ThreadListResponse,
    ToolCallRecord,
    Trade,
    TradingProfile,
)
from src.web.schemas.agent import (
    ConfidenceResult,
    DataReference,
    DimensionAnalysis,
    RiskWarning,
    TargetPrice as UnifiedTargetPrice,
    UnifiedAnalysisResult,
)
from src.web.schemas.versioning import (
    ConfidenceMetadata,
    SchemaVersion,
    TrustZone,
    VersionedSchema,
    build_confidence_metadata,
    compute_trust_zone,
)
from src.web.schemas.lineage import (
    DataSnapshot,
    LineageGraph,
    LineageNode,
)
from src.web.schemas.capital import (
    CapitalBalance,
    CapitalBreakdown,
    CapitalHistoryResponse,
    CapitalTransaction,
    DepositRequest,
    PositionCapital,
    WithdrawRequest,
)
from src.web.schemas.strategy import (
    AIAttributionRequest,
    AIAttributionResult,
    AIOptimizationRequest,
    AIOptimizationResult,
    CheckSignalsRequest,
    LatestSignalItem,
    NLStrategyRequest,
    NLStrategyResult,
)
from src.web.schemas.registry import (
    SchemaRegistry,
    SchemaValidationResult,
)
from src.web.schemas.agent_io import (
    AgentInputBase,
    AgentOutputBase,
    DataLineageRef,
    register_all_schemas,
)
from src.web.schemas.market_signal import (
    MarketPhase,
    MarketSignal,
    PushDecision,
    RiskContext,
    RiskLevel,
    SignalType,
    SourceReference,
)
from src.web.schemas.user_config import (
    NotificationPrefs,
    UserFollows,
)

__all__ = [
    # advisor
    "StockAdviceResult",
    "WatchlistStrategyItem",
    "WatchlistStrategyResult",
    "PositionAdvice",
    "PortfolioAdviceResult",
    "PortfolioAdviceRequest",
    "HolidayImpactFactor",
    "HolidayImpactResult",
    "PositionImpact",
    "ReopenBriefingResult",
    "QuantSignals",
    "TargetPrice",
    # sentiment / cross-market
    "ResonanceTimelineEntry",
    "ResonanceEventItem",
    "ResonanceResult",
    "SentimentCoreTrend",
    "SentimentPolicySignal",
    "SentimentGlobalLinkage",
    "SentimentRiskAlert",
    "SentimentSectorOutlook",
    "SentimentReportResult",
    "CrossMarketPeer",
    "CrossMarketGroup",
    "CrossMarketResult",
    # common
    "ApiResponse",
    "MarketAIOverview",
    # stock
    "WatchlistItem",
    "StockDetail",
    "OHLCVRecord",
    "IndicatorsSummary",
    "IndicatorsFullRecord",
    "PatternDetection",
    "SupportResistanceLevel",
    "RealtimeQuote",
    "StockSearchItem",
    "IntradayTradesStats",
    "TickRecord",
    "IntradayTradesSnapshot",
    "QuoteSnapshot",
    "FundFlowSnapshot",
    "FundFlowDetailSnapshot",
    "RealtimeSnapshot",
    # market
    "DragonTigerItem",
    "LimitUpItem",
    "MarketIndex",
    "HotRankItem",
    "DragonTigerSeatItem",
    "DragonTigerStockStats",
    "DragonTigerAIResult",
    "GlobalIndexItem",
    "GlobalCommodityItem",
    "GlobalCurrencyItem",
    "GlobalMarketSnapshot",
    "TradingCalendarInfo",
    # fund_flow
    "FundFlowItem",
    "FundFlowDetail",
    "SRKeyLevel",
    "SRAnalysisResult",
    # prediction
    "PredictionRequest",
    "PredictionResult",
    "QuickInsight",
    "EnhancedPredictionRequest",
    "ComparisonPredictionRequest",
    "EnhancedPredictionResult",
    "ComparisonPredictionResult",
    # portfolio
    "PortfolioPosition",
    "PortfolioData",
    "PortfolioPositionInput",
    "PortfolioDiagnosisRequest",
    "PositionAdviceItem",
    "ConcentrationRisk",
    "PortfolioDiagnosisResult",
    # backtest
    "StrategyInfo",
    "BacktestRequest",
    "BacktestMetrics",
    "BacktestResponse",
    "BacktestInterpretRequest",
    "BacktestInterpretResult",
    "StrategyFlowStep",
    "StrategyFlowEdge",
    "StrategyParam",
    "StrategyMetadataResponse",
    "TradeSignalItem",
    "RoundTripItem",
    "AttributionData",
    "BacktestRequestV2",
    "BacktestResponseV2",
    # analysis
    "IndicatorProbabilities",
    "BayesianIndicatorItem",
    "BayesianComposite",
    "BayesianAnalysisResult",
    "MoveAnalysisRequest",
    "MoveAnalysisFactor",
    "MoveAnalysisPositionContext",
    "MoveAnalysisResult",
    "ChartEvent",
    "ChartEventsResult",
    "AIAnalysisResult",
    "Alert",
    "IndicatorExplanation",
    # news
    "StockNewsItem",
    "AnomalyItem",
    "SentimentSummary",
    "ResearchResult",
    # notification
    "NotificationItem",
    "UnreadCountResponse",
    # admin
    "ApiKeyInfo",
    "AddKeyRequest",
    "UsageDashboard",
    "RoutingConfig",
    "UpdateRoutingRequest",
    # settings
    "UpdateConfigRequest",
    "WatchlistAddRequest",
    "WatchlistRemoveRequest",
    "WatchlistUpdateRequest",
    # scheduler
    "SchedulerStatus",
    "TaskConfig",
    "SchedulePlan",
    "SchedulePlansResult",
    "CalendarDay",
    "CalendarResult",
    "UpdatePlanRequest",
    "SentinelConfig",
    "NotificationChannelConfig",
    # concept
    "ConceptLeader",
    "ConceptHeatResponse",
    "ConceptHeatListResponse",
    "ConceptConstituentItem",
    "ConceptHistoryRecord",
    "StockConceptItemResponse",
    "ResonanceResponse",
    "StockConceptsResponse",
    # holiday_research
    "ConversationMessage",
    "UserNote",
    "AddNoteRequest",
    "HolidayResearchContext",
    "BusinessFactor",
    "SectorAnalysis",
    "PeerComparison",
    "RiskItem",
    "ReopeningStrategy",
    "ComprehensiveAnalysisResult",
    "FollowupRequest",
    "FollowupResponse",
    # holiday_research v3.4
    "AssociationProfileResponse",
    "ConceptLinkResponse",
    "PeerLinkResponse",
    "IndustryProfileResponse",
    "ResearchQuestion",
    "ResearchChecklist",
    "EvidenceItem",
    "AddEvidenceRequest",
    "Scenario",
    "ScenarioPriceImpact",
    "ScenarioResult",
    "ScenarioAnalysisRequest",
    "ScenarioAnalysisResult",
    # holiday_research profile overrides
    "ProfileOverrideConceptItem",
    "ProfileOverridePeerItem",
    "ProfileOverrideRequest",
    "ProfileOverrideResponse",
    # strategy
    "NLStrategyRequest",
    "NLStrategyResult",
    "AIOptimizationRequest",
    "AIOptimizationResult",
    "AIAttributionRequest",
    "AIAttributionResult",
    "LatestSignalItem",
    "CheckSignalsRequest",
    # agent (v8.0 unified)
    "UnifiedAnalysisResult",
    "DimensionAnalysis",
    "ConfidenceResult",
    "DataReference",
    "RiskWarning",
    "UnifiedTargetPrice",
    # conversation (v11.0)
    "ConversationRequest",
    "PositionContext",
    "ConversationMessageItem",
    "ConversationResponse",
    # chat (v12.0)
    "ChatThread",
    "ChatMessage",
    "RichCard",
    "ToolCallRecord",
    "ThreadContext",
    "CreateThreadRequest",
    "CreateThreadResponse",
    "SendMessageRequest",
    "ThreadListItem",
    "ThreadListResponse",
    "Trade",
    "TradingProfile",
    # versioning (v14.0)
    "VersionedSchema",
    "SchemaVersion",
    "ConfidenceMetadata",
    "TrustZone",
    "compute_trust_zone",
    "build_confidence_metadata",
    # lineage (v14.0)
    "DataSnapshot",
    "LineageNode",
    "LineageGraph",
    # capital
    "CapitalTransaction",
    "CapitalBalance",
    "CapitalBreakdown",
    "PositionCapital",
    "DepositRequest",
    "WithdrawRequest",
    "CapitalHistoryResponse",
    # schema registry (v18.0)
    "SchemaRegistry",
    "SchemaValidationResult",
    # agent I/O (v18.0)
    "AgentInputBase",
    "AgentOutputBase",
    "DataLineageRef",
    "register_all_schemas",
    # market signal (v20.0)
    "SignalType",
    "RiskLevel",
    "MarketPhase",
    "PushDecision",
    "SourceReference",
    "RiskContext",
    "MarketSignal",
    # user config (v20.0 Phase 4)
    "UserFollows",
    "NotificationPrefs",
]
